batch_size: 16                         # batch size                            # warm-up epochs
epochs: 50                            # total number of epochs
warm_up: 15
load_model: None                        # resume training
eval_every_n_epochs: 1                  # validation frequency
save_every_n_epochs: 5                  # automatic model saving frequecy


init_lr: 0.0001                         # initial learning rate for Adam
weight_decay: 1e-4                      # weight decay for Adam
gpu: cuda:0                             # training GPU 


model: 
  num_layer: 5                          # number of graph conv layers
  emb_dim: 128                          # embedding dimension in graph conv layers
  feat_dim: 64                         # output feature dimention
  drop_ratio: 0.1                         # dropout ratio                     
  gene_number: 978
  queue_size: 64                         # batch size
  bidirectional: False
  hid_dim: 128
  dim: 256
  num_layers: 5
  AUTO_activation: 'leakyrelu'
  hid_dim: 128
  n_heads: 2
  dropout: 0.1

                              # molecule graph augmentation strategy (i.e., node/subgraph/mix)
dataset:
  num_workers: 0                       # dataloader number of workers                   
  data_path: ./data/random_test.csv # path of data(e.g.random_train.csv,scaffold_train.csv)
  data_path_4: ./protein_embedding_esm2_max1024
loss:
  temperature: 0.1                      # temperature of NT-Xent losss
